apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: test-simple-build-efea
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/tnevrlka-test/build-e2e-tjdp-tenant/build-suite-test-application-emit/test-simple-build-efea@sha256:1501ebe13304970ceba32314605ba6ee6e9017757169e9733662bd423d9a72a8
        name: my-nginx
        resources: {}
status: {}
