apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-simple-build-efea
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-simple-build-efea
    app.kubernetes.io/part-of: build-suite-test-application-emit
  name: test-simple-build-efea
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: test-simple-build-efea
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: test-simple-build-efea
    spec:
      containers:
      - image: quay.io/tnevrlka-test/build-e2e-tjdp-tenant/build-suite-test-application-emit/test-simple-build-efea@sha256:2b9a8e89c6299d70bc423b22d1b13890c72d480b99780141a5ebdafa0b420577
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
